### ISSUE TITLE
update hexo-fs to 0.2.0

### ISSUE THREAD

**Issue by dlmyb** [Rozbo/hexo-abbrlink#12]
https://github.com/hexojs/hexo/issues/2847

**Comment by mapxn** [comment]
```
(node:7012) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
```
此API在node.js 8.0+版本中已弃用，请更新插件中的hexo-fs@^0.2.2

**Comment by mapxn** [comment]
```
+-- hexo-abbrlink@2.0.4
| `-- hexo-fs@0.1.6
```

**Comment by ohroy** [comment]
fixed

**Comment by nyxzer0** [comment]
为啥现在npm install hexo-abbrlink --save 后还是出这个问题，
![default](https://user-images.githubusercontent.com/10548441/33756791-0c9c4bfa-dc32-11e7-8085-864bb9514e78.png)
啥时候到2.0.5

**Comment by ohroy** [comment]
@nyxzer0 好了，之前忘记发布到npm了。
