### ISSUE TITLE
启用hexo-abbrlike插件后会修改图片存储路径，是否有自动化的解决方案？

### ISSUE THREAD

**Issue by sjkcdpc** [Rozbo/hexo-abbrlink#13]
在使用插件之前在文章中嵌入图片语法如下
``` text
![](/hexo部署教程/02.jpg)
```
生成静态页面后images存储路径不变

使用插件后
生成静态页面的images存储路径变为了
``` text
![](/9f2323d4/02.jpg)
```
导致原来写的文章都找不到images，导致线上失败
问有没有比较好的解决方案避免这个问题
不知道有没有表达清楚 我的qq 1455975151

**Comment by 777Arch** [comment]
遇到同样的问题，同问。

**Comment by ohroy** [comment]
暂无自动化解决方案，建议图片和文章链接不要进行挂钩。
