### ISSUE TITLE
重新生成链接

### ISSUE THREAD

**Issue by anson2416** [Rozbo/hexo-abbrlink#14]
我生成一个文章的时候，有时候因为1）文章名字不合法（例如包含：在windowns系统），2）修改了文章名字，这样文章就不能生成AbbrLink链接。请问怎样手动重新生成？

**Comment by ohroy** [comment]
一般意义上来讲，一旦生成了链接，则无需修改，因为他只有第一次运算与标题有关，后续标题改变，链接也不会重新生成，这么做的意义在于链接要尽量保持固定，以免各种404死链的产生。  
然而，如果你执意要进行修改，只需要打开这篇文章.md，在文章的顶部的front-matter里，找到`abbrlink: `后面的数字，修改即可。  
如果你这么做了，你甚至可以将数字修改为其他字符，如字母，这样，即实现了个性化链接。

**Comment by anson2416** [comment]
我想请教下，abbrlink的运行机制？例如是在什么命令后生成链接的。有时候我new一个文章后，链接并没有生成。

**Comment by ohroy** [comment]
[https://post.zz173.com/detail/hexo-abbrlink.html](https://post.zz173.com/detail/hexo-abbrlink.html)

**Comment by anson2416** [comment]
谢谢答疑！
