### ISSUE TITLE
文章返回404

### ISSUE THREAD

**Issue by hao14293** [Rozbo/hexo-abbrlink#15]
把_config.yml中 permalink: year/:month/:day/:title/ 改为permalink: year/:month/:day/:addrlink/后，文章返回404,这是为什么。

**Comment by ohroy** [comment]
这个问题，测试未能复现

**Comment by hao14293** [comment]
已经解决，是浏览器缓存的问题

2018-03-28 16:20 GMT+08:00 落月 <notifications@github.com>:
