### ISSUE TITLE
希望采用文件创建的时间戳作为永久链接

### ISSUE THREAD

**Issue by webees** [Rozbo/hexo-abbrlink#16]
一般来说创建时间不会修改，所以作为永久链接非常适合。其次也赋予url一定意义，使其和文章也有一点的关联性。

**Comment by ohroy** [comment]
当时考虑过这个，但因为时间戳太长了，最后没有使用。

**Comment by webees** [comment]
crc32 & dec 也很长啊。秒级时间戳就够用了。

**Comment by ohroy** [comment]
一般地，建议使用crc16

**Comment by bejondshao** [comment]
生成链接后如果更改文章标题或者更改md文件名， 链接仍然有效吗

**Comment by ohroy** [comment]
@bejondshao yes
