### ISSUE TITLE
不建议强行重写 .md 源文件

### ISSUE THREAD

**Issue by xu-song** [Rozbo/hexo-abbrlink#17]
看了一下实现，其中把abbrlink写入到了.md文件中，同时也改动其他文本格式（比如CRLF与LF之间的替换 ）。

建议：
- 与hexo动态交互，而不是把link写入到md静态文件
- link的复用可以采用独立的数据文件，不侵入源文件

当然重写有很多好处，但是觉得不够优雅

菜鸟愚见，逃

**Comment by ohroy** [comment]
hexo因为足够轻量，没有独立的数据库，所有的数据都存在`.md`当中，`.md`在这里分为两部分，上面的叫`front-matter`，这部分本来就是充当数据库来使用。  
当然，自己重新实现一个数据库也是充分考虑过的，但是由于没有对应关系，固定链接和谁对应？标题？还是创建时间？还是其他的什么？因为这一切都是可能被修改的，而固定链接绝对不能因为这些属性被修改就重新生成。
综上，直接写入`front-matter`无疑是现阶段的最优方案。
