### ISSUE TITLE
非常感谢作者，但是当有图片存在时，有bug

### ISSUE THREAD

**Issue by znmlr** [Rozbo/hexo-abbrlink#19]
非常感谢作者！！
我同时使用了``hexo-asset-image``和你的``hexo-abbrlink``，这2个插件对我帮助很大

``hexo-asset-image``的逻辑大概如下
- ``hexo n title``时，会在_post下新建title.md文件和同名的title文件夹
- 编辑md时，如果需要插入图片，我们可以手动拷贝文件到title文件夹中
- ``hexo g``时，会自动拷贝同名文件夹到public恰当位置

但是用了``hexo-abbrlink``后，这个机制被破坏了
例如我新建了一篇``测试.md``，而``hexo-abbrlink``把它url转为``13432.html``，那么在拷贝图片时，会拷贝到13432文件夹中。而md文档转为html文件时，用的相对路径还是类似"测试/1.png"，导致图片全部显示失败

能否在拷贝同名文件夹时，不要转名字，保留原始名字，这样方便存放图片，非常感谢！！

**Comment by ohroy** [comment]
首先很高兴你能希望这个小工具，也很感谢你提交这个`issue`，能清晰的描述出问题所在，让我找到这些问题的答案  
#13 
看来，这里面涉及到人们的一个糟糕的心理上的弱点，即是守旧心里。简而言之，就是对新事物总是持有怀疑。你还算是比较客观的，如上哪位仁兄，根本就没提另外一个插件这一茬。  
**显然你们都认为是这个插件让一切变得糟糕，原因是本插件后安装的。**  
事实上这并不符合逻辑，在本插件的中文说明里，详细介绍了本插件的原理和开发历程及逻辑，本插件从没有创建文件，也不会对文件改名。
插件的原理不再赘述，但我想可以给你解释以下`hexo`的逻辑，因为最终生成的博客是`html`格式，要想让链接能顺利被访问到，就必须保证文件目录和网址的对应关系。那么，当你设置了固定链接格式为
```
:abbrlink/
```
就必然要对应
```
xxxxx/index.html
```
这样的网址，就必然要生成
```
-- xxx
---- index.html
```
这个的文件格式。

这一切是由`hexo`的核心逻辑处理，这一切并没有什么问题，而且非常符合逻辑。

-----

现在，你该知道怎么办了吧？解铃还须系铃人啊。

**Comment by znmlr** [comment]
感谢作者的回复，也认可你的分析，但是不太认可你的结论

咱们这样分析吧，这事儿一共有4个相关方
1、hexo
2、hexo-asset-image
3、hexo-abbrlink
4、博客作者

咱们用排除法，先把4和2去掉，理由
4：操作过程中已经遵守说明，并无不当
2：这个插件仅仅是在新建文档的时候起作用，不参与生成与部署

那么从解决问题的角度而言，只有1或3能够处理这个问题，而且从技术上来说，1和3都可以处理这个问题。你觉得哪方处理更合适呢？
我个人觉得3处理更合适，因为文档通过插件处理后，在顶部增加了一些静态数据，根据这些数据生成静态页面名字的，这个过程显然3更加熟悉。

**Comment by ohroy** [comment]
在技术的角度上讲，**写**操作的非常危险的，也是要负责任的。`谁创建谁负责，谁申请谁释放`，这是一个**基本原则**。  
因为要照顾到没有使用这个插件的人，或者固定链接不是`:abbrlink/`的用户，本插件不会做其他人应该做的事情。   
谢谢你的支持。

**Comment by znmlr** [comment]
好吧，尊重作者的观点
我只好自己写了一个nodejs脚本，在图片上点击右键直接上传到腾讯COS中，自动在剪切板里面生成md格式的图片链接，大概这样的
``![Hexo建站笔记](https://***.cos.ap-shanghai.myqcloud.com/2018/05/***.png)``，然后在typora中粘贴即可

**Comment by mapxn** [comment]
> 感谢作者的回复，也认可你的分析，但是不太认可你的结论
> 
> 咱们这样分析吧，这事儿一共有4个相关方
> 1、hexo
> 2、hexo-asset-image
> 3、hexo-abbrlink
> 4、博客作者
> 
> 咱们用排除法，先把4和2去掉，理由
> 4：操作过程中已经遵守说明，并无不当
> 2：这个插件仅仅是在新建文档的时候起作用，不参与生成与部署
> 
> 那么从解决问题的角度而言，只有1或3能够处理这个问题，而且从技术上来说，1和3都可以处理这个问题。你觉得哪方处理更合适呢？
> 我个人觉得3处理更合适，因为文档通过插件处理后，在顶部增加了一些静态数据，根据这些数据生成静态页面名字的，这个过程显然3更加熟悉。

---
@znlmr 回复一下，和题主的观点恰恰相反，个人认为1和3 不应该去解决该问题，真正能解决问题是是2和4。一个插件仅仅做到该插件的最基础功能的应该实现的功能就好，做到高内聚，低耦合。这个问题我也遇到了，自己琢磨了一下，不用些什么node.js代码。** 仅仅需要修改 2插件<hexo-asset-image>中的2行代码即可 ** 。 

# 方法如下
编辑`xxx\node_modules\_hexo-asset-image@0.0.3@hexo-asset-image\index.js`文件
1、在源码的12行附近`var link = data.permalink;`这一行的下面，**添加** 一行`var abbrlink = data.abbrlink`
（意思是定义一个变量abbrlink）
2、在44行附近，源码的` $(this).attr('src' , '/' + link + src);`这一行，**修改** 为下面一行：
` $(this).attr('src' , '/' + link + abbrlink + '/' + src);`
（意思是生成的图片链接中，拼接abbrlink）

然后重新hexo clean 和 hexo g，即可生效。
_posts文件夹下的文章，按照自己喜欢的方式整理，生成的链接是正常的，在typora中可以正常显示。

---

如果想typora中黏贴后自动复制到正确路径（懒人模式），需要以下设置：
typora中需要设置
![image](https://user-images.githubusercontent.com/16299874/57820127-06051a00-77be-11e9-9046-8a953285ae61.png)

![image](https://user-images.githubusercontent.com/16299874/57820135-0ef5eb80-77be-11e9-85d5-956bdf034a57.png)

希望可以帮到一些人。

**Comment by foreveryang321** [comment]
我修改的版本：https://github.com/foreveryang321/hexo-asset-image

**Comment by unix2dos** [comment]
如果你的permalink加了后缀的话,   例如我的 `permalink: p/:abbrlink.html`
编辑xxx\node_modules\_hexo-asset-image@0.0.3@hexo-asset-image\index.js文件, index多减个值

```
    if(/.*\/index\.html$/.test(link)) {
      // when permalink is end with index.html, for example 2019/02/20/xxtitle/index.html
      // image in xxtitle/ will go to xxtitle/index/
      appendLink = 'index/';
      var endPos = link.lastIndexOf('/');
    }
    else {
      // var endPos = link.length-1; // 换成下面的这句话
      var endPos = link.length-5; //因为我的permalink: p/:abbrlink.html,  这里要改成-5
    }
```

**Comment by Myoontyee** [comment]
> 我修改的版本：https://github.com/foreveryang321/hexo-asset-image

按你的配置，有时候行，有时候不行，如下图，有时候没有生成正常的图片链接，不知道为啥

![图片](https://user-images.githubusercontent.com/40823733/232539715-5294e92c-c0aa-4371-8713-3d9635d41412.png)
