### ISSUE TITLE
post/undefined

### ISSUE THREAD

**Issue by iCocos** [Rozbo/hexo-abbrlink#21]
遇到了个问题，按照你的步骤，对应的内容显示post/undefined
这是我的源内容，
permalink: posts/:abbrlink/ 
permalink_defaults:
# abbrlink config
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32 
  rep: hex    # 进制：dec(default) and hex
已执行安装：npm install hexo-abbrlink --save

**Comment by ohroy** [comment]
可能那里报错了吧。。没发现这个
