### ISSUE TITLE
Some post files cannot be resolved, when its front-matter contains true.

### ISSUE THREAD

**Issue by YodesYang** [Rozbo/hexo-abbrlink#22]
问题描述： 当Front-matter包含布尔表达式时，无法生成对应的abbrlink number，此类文件将被程序忽略。此外每次 hexo g /  hexo s 时好费时间啊！
未被解析的Front-matter示例：
```
---
comment: true
layout: true
---
```

**Comment by ohroy** [comment]
慢是有可能的。。但bool的这个，没见其他人反映过。。
