### ISSUE TITLE
改了配置怎么强制再次生成？

### ISSUE THREAD

**Issue by think2cat** [Rozbo/hexo-abbrlink#23]
修改了生成文件名配置，怎么强制再次生成？

**Comment by think2cat** [comment]
用notepad++批量查找替换把abbrlink属性去掉了 ☕️

**Comment by ohroy** [comment]
#25 
会考虑增加这个功能。。。虽然你的方法也挺不错的。

**Comment by ohroy** [comment]
https://github.com/rozbo/hexo-abbrlink/commit/d19113ab4dab68101e11183a38f2665b9ebf9e5f
已增加此功能，详情看文档
