### ISSUE TITLE
我希望强制重新生产addrlink

### ISSUE THREAD

**Issue by chenghm123** [Rozbo/hexo-abbrlink#25]

**Comment by chenghm123** [comment]
能否加入配置

**Comment by EscapeLife** [comment]
@rozbo  提几点实用性的需求，希望有时间能够加一下，感谢哈！

1. 能够提供重新生产addrlink的功能
2. 能够提供删除文章中addrlink的功能，不然生产之后，手动删除很费劲的
3. 如果后续文章中的addrlink出现重复的话，系统能够给出提示，便于自行修改

最后，小花花，送给你哈。

![image](https://user-images.githubusercontent.com/16237571/45291156-ef6a3d00-b523-11e8-87cc-75a337bfa31f.png)

**Comment by ohroy** [comment]
重新生成这个理论上来说可能能实现，但不太友好。
我再想想。
另外，重复的问题理论上是不太可能的，现在的逻辑是避免重复，而不是重复提示。

**Comment by ohroy** [comment]
已经增加了强制模式，用来重新生成。https://github.com/rozbo/hexo-abbrlink/commit/d19113ab4dab68101e11183a38f2665b9ebf9e5f
