### ISSUE TITLE
几条建议

### ISSUE THREAD

**Issue by Aqua-Dream** [Rozbo/hexo-abbrlink#27]
第一，CRC16或者32都有重复的可能，如果有重复，应该要在控制台提示到用户。仅仅重新分配的话，如果新写的文章和以前的重复且将以前文章的链接修改了，那么原来存在的指向该文章的链接都会出错，且用户并不知道。

第二，说明文档中指出crc16的重复概率是1/65536，但多篇文章全都不一样的概率不能这么算。文章数量到大约根号级别，即256篇文章的时候，重复概率已经很大了(40%)。所以建议还是使用CRC32。如果嫌8个字符的hex表示长的话，可以考虑将Int.toString(16)改成toString(36) （最大只能填36），这样可以包括所有小写和数字，大约可以省下2个字符…… 甚至可以自己写个函数把大写字母再加入（这个就不展开了）。

第三，其实CRC32之类的hash不是唯一选择，对于字符串的情形我们有一个比较通用的hash方法，见[Generate a Hash from string in Javascript](https://stackoverflow.com/questions/7616461/generate-a-hash-from-string-in-javascript)。最佳答案给出的代码也是返回一个32-bit的整数，和CRC32的范围相同。

``` javascript
String.prototype.hashCode = function() {
  var hash = 0, i, chr;
  if (this.length === 0) return hash;
  for (i = 0; i < this.length; i++) {
    chr   = this.charCodeAt(i);
    hash  = ((hash << 5) - hash) + chr;
    hash |= 0; // Convert to 32bit integer
  }
  return hash;
};
```

第四，蛮多人问`undefined`的问题的，考虑在说明中加入一下`hexo clean`？

**Comment by ohroy** [comment]
回复123，可能是readme里的说明有误，实际上代码是有重复检测的，当重复时，会自动+1尝试，知道遇到一个不重复的为止。
回复1234，这是readme的毛病，我太懒了。没有修改。你可以提交pr或等我有一天醒悟的时候。

**Comment by Aqua-Dream** [comment]
关于重复检测，我的意思是你（应该）不能确定文章到来的顺序，就有可能发生如下错误？

文章1->id1
外部链接引用id1

然后某天写了文章2，生成时

文章2->id1
文章1->id1+1
外部链接引用出错

**Comment by ohroy** [comment]
为什么要文章2变成id1，而不是文章2直接为id1+1 ？？？

**Comment by Aqua-Dream** [comment]
你生成的时候知道哪个是文章1哪个是文章2？每次生成不是重新建一个set，往里面加文章ID吗？还是说你有把这个set持久化存储？

**Comment by ohroy** [comment]
刚才仔细看了下代码，当先处理新文章时确实会导致bug。欢迎提交pr。

**Comment by Aqua-Dream** [comment]
不太会写代码 = = 等有缘人来改吧

**Comment by ohroy** [comment]
https://github.com/rozbo/hexo-abbrlink2 中，链接有序增长，变相解决此问题。
