### ISSUE TITLE
有冲突，不知有办法解决 吗？

### ISSUE THREAD

**Issue by KumaNNN** [Rozbo/hexo-abbrlink#30]
首先，你的这插件很好，很利于SEO。
但是，另一款插件：  [HEXO-自动分类 ](https://github.com/xu-song/hexo-auto-category)   也是我喜欢用的，它是按文件目录结构自动生成分类的。

你们这2款插件都是读写  `Front-matter` 的数据。
现在，有个问题，如果同时启用这2个插件，会导致，你的这个插件无法向 md 文件里写入 abbrlink 属性。
而且，在 hexo s  运行下，会死循环似得，执行插件的动作，对随机某个md文件。

不知道有没有办法，兼容这2个插件呢？

hexo-abbrlink  ： 利于SEO
hexo-auto-category ： 方便管理分类

按理来说，这2个插件都可用的啊，因为最终生成的是由 permalink 属性决定的。

**Comment by KumaNNN** [comment]
~~都是读写 Front-matter 的数据，可能是没有锁导致数据丢失吧，我猜的。~~

刚才测试了下： 优先级数字大，即后面执行的，优先级低的，才能把data 数据保存到文件中。
意思就是 :  data好像是同时分发的。后面的插件拿的data还是原始的，不是上一个插件修改后的data。

看来，只能把别人的代码 **吃了**。。。

**Comment by ohroy** [comment]
可能是hexo api的bug吧，理论上应该是依次执行的。
我没有用过这个插件，但是理论上来说，应该插件是无法干涉hexo本身的流程的吧。

**Comment by yqs112358** [comment]
abbrlink有内置的auto_categories功能了
或者可以用这个：[hexo-directory-category](https://github.com/zthxxx/hexo-directory-category)
