### ISSUE TITLE
请问能否对原链接进行自动重定向呢？

### ISSUE THREAD

**Issue by rxliuli** [Rozbo/hexo-abbrlink#32]
如题，例如原本没有使用 hexo-abbrlink 之前，生成的文章已经存在了很长的时间，现在使用了之后链接全部发生了变化，能否实现在访问原页面时自动重定向短链接呢？ヾ(@^▽^@)ノ

**Comment by ohroy** [comment]
这个理论上是可行的，待我抽出时间搞一下。

**Comment by ohroy** [comment]
经过尝试，实现此功能较为复杂，还不如手动复制一份来得实在

**Comment by rxliuli** [comment]
> 经过尝试，实现此功能较为复杂，还不如手动复制一份来得实在

去年的 issue，吾辈早已经没关注这个了 #笑哭

**Comment by hubojing** [comment]
如果不重定向，以前的阅读量计数都会丢失了呀
