### ISSUE TITLE
 关于 hexo-abbrlink 和 hexo-asset-image 同时使用的图片显示问题

### ISSUE THREAD

**Issue by JunqiFu** [Rozbo/hexo-abbrlink#33]
作者的插件写的非常棒，但是还是针对于 和 hexo-asset-image  同时使用的问 带给人非常大的困扰，对于一个刚刚接触 hexo的新人，原谅我实在没有看懂其他提问者的解决方式，希望作者能不能优化一下呢？
   另外就是，如何做到关闭你的插件呢？我尝试删除 文章 头部 abbrlink:   属性和 修改 permalink: posts/:abbrlink/  但是，abbrlink: 依然会重新生成，并且导致文章目录和内容错乱，能否做到当我使用了hexo-asset-image插件时，能够在hexo配置文件_config.yml中实现关闭 hexo-abbrlink插件呢？
       ps: 我临时的解决让图片显示的方式是：在_posts文件下建立一个和文章abbrlink:  属性名字相同的文件夹，将图片放在这个文件夹中，修改图片的地址到这个文件下图片就能重新显示了，但是这个方法需要我每建一篇新的文章需要建立一个以文章abbrlink:  属性 为名字的问件夹，所以希望作者能针对于此做出优化，另外，如果实在不能改变，也希望作者在介绍中明确阐述，不能和hexo-asset-image 插件同时使用

**Comment by ohroy** [comment]
这个已经做了多次说明了。

具体见 #19 #26 #13 

但是我还是很纳闷，谁能给我解释一下，图片显示不了为什么不去找做图片插件的，找我干嘛？？？

**Comment by qiXiaoFanTomato** [comment]
哈哈哈哈笑死我了
