### ISSUE TITLE
采用该插件后，文章Front-matter  permalink 貌似就失效了

### ISSUE THREAD

**Issue by bigcoder84** [Rozbo/hexo-abbrlink#34]
大佬感谢您的付出为我们贡献了一个优秀的永链解决方案，但是貌似使用这个插件后，每篇文章都会使用abbrlink作为链接地址。我现在有这么个需求，需要给博客添加一个“关于”页面，链接为/about；但是我在Markdown文件的Front-matter部分添加permalink: /about，但是这样做起不到任何作用（通过/about访问不到页面）。

**Comment by ohroy** [comment]
参见hexo文档，像`关于`这种自定义的页面应该是page而不是post

**Comment by bigcoder84** [comment]
> 参见HEXO文档，像`关于`这种自定义的页面应该的英文页面而不是交

非常感谢😊😊😊
