### ISSUE TITLE
Some vulnerabilities require your attention to resolve（需要解决脆弱性问题）

### ISSUE THREAD

**Issue by scarleast** [Rozbo/hexo-abbrlink#36]
<img width="903" alt="截屏2019-12-25下午11 55 44" src="https://user-images.githubusercontent.com/14150292/71448098-57bd4c00-2772-11ea-91ba-b9222bbe5bfa.png">

I wonder if it can be solved?
不知道能不能解决下？

**Comment by ohroy** [comment]
fixed
