### ISSUE TITLE
我按照给的方法添加配置后生成链接都是undefined

### ISSUE THREAD

**Issue by FENG1000** [Rozbo/hexo-abbrlink#37]
检查了下原来的博客`.md`文件中也都没生成`abbrlink`这个属性，尝试新增一篇博客也没有`abbrlink`这个属性，我想问下这个是需要自己手动填写吗

**Comment by FENG1000** [comment]
这个是我添加的配置
```ymal
permalink: posts/:abbrlink.html

# abbrlink config
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
```
生成后的页面链接
> http://localhost:4000/posts/undefined.html

**Comment by yansheng836** [comment]
```bash
hexo clean
hexo s
```

**Comment by yansheng836** [comment]
Duplicated 
see <https://github.com/rozbo/hexo-abbrlink/issues/7#issuecomment-419828868>

**Comment by imldy** [comment]
clean一下重新生成

**Comment by FENG1000** [comment]
已经解决创建的文章中不能设置layout，将layout属性删掉后就可以正常生成了

**Comment by MrBaize** [comment]
你好！我也是同样的问题。请问文章layout属性在哪删除？

**Comment by xljya** [comment]
> 你好！我也是同样的问题。请问文章layout属性在哪删除？

我的修改方式不太一样，在hexo new后创建的文章的最上方设置layout : false，然后hexo c&&g，之后hexo s发现文章乱码，删除掉layout : false，继续hexo c&&g，旧文章就改成新的随机链接了。
