### ISSUE TITLE
生成的链接为null

### ISSUE THREAD

**Issue by geekqian** [Rozbo/hexo-abbrlink#39]
如题, 生成的不是 **undefined**, 而是 **null**. 
步骤就是 `hexo clean`  然后` hexo g ` .
之前 Hexo 3.8.0 的版本没问题, 不知道是不是升级到 4.2.0 的版本后的冲突. 

![image](https://user-images.githubusercontent.com/15983385/76046285-76be3280-5f9a-11ea-9262-4110a137eeb8.png)

**Comment by ohroy** [comment]
更新后测试没问题，你也可以升级到最新版试试，
