### ISSUE TITLE
序列增长具有随机性

### ISSUE THREAD

**Issue by achenger** [Rozbo/hexo-abbrlink#43]
请问插件生成的固定链接可以做到有序增长么，如20,21,23，... ，1427,1428这样；

或者有何其他方案可以实现上述功能。

**Comment by KumaNNN** [comment]
好像是基于文件名或title的内容来生成的。。。

**Comment by ohroy** [comment]
针对此需求另开发了个插件
https://github.com/rozbo/hexo-abbrlink2
