### ISSUE TITLE
cannot deploy with Vercel

### ISSUE THREAD

**Issue by gaminglifex** [Rozbo/hexo-abbrlink#62]
![image](https://user-images.githubusercontent.com/72642816/153228930-def908d6-3a12-496b-9d39-d2633b7b2779.png)
The error occur when deploying Hexo using Vercel with abbrlink plugin. 
cannot figure out the solution atm

**Comment by ohroy** [comment]
this error tips usually means the yaml configuration file format is wrong
pls check again

**Comment by gaminglifex** [comment]
Thank you for your reply.
I found that it only worked when it is local:
![image](https://user-images.githubusercontent.com/72642816/153695794-33508e6c-450f-4a2d-923d-c47244e61984.png)

and my yaml configuration is as below:
![image](https://user-images.githubusercontent.com/72642816/153695805-980708df-650e-4e96-90e4-6f077b6a5089.png)
Is my configuration correct?

**Comment by gaminglifex** [comment]
oops, somehow it worked. The only thing I did is just updating hexo to 6.0.0 version
Thank you btw
