### ISSUE TITLE
安装完成后都是undefined.html

### ISSUE THREAD

**Issue by mant7s** [Rozbo/hexo-abbrlink#7]
按照教程安装后，修改了permalink: posts/:abbrlink.html

然后连接都变成了http://xxx.com/posts/undefined.html

**Comment by ohroy** [comment]
可能你没有安装成功吧?
`undefined`代表未定义的。

**Comment by mant7s** [comment]
已经安装成功了，package.json里面依赖包也都显示有数据；
```
"dependencies": {
    "hexo": "^3.2.0",
    "hexo-abbrlink": "^2.0.4",
    "hexo-deployer-git": "^0.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.0",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-prism-plugin": "^2.0.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-jade": "^0.3.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-sass": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
```

**Comment by ohroy** [comment]
那你仔细观察下在生成过程中有报错吗？

**Comment by mant7s** [comment]
这是安装命令打出来的：
![image](https://user-images.githubusercontent.com/8286273/28111869-8f84273c-6729-11e7-926f-3d58cc865017.png)
文件也都在：
![image](https://user-images.githubusercontent.com/8286273/28111981-f51b1aec-6729-11e7-9ee7-3b9e2fc81e8a.png)

**Comment by ohroy** [comment]
我指的是在文章的生成过程中....

**Comment by popy32** [comment]
clear the cache and regenerate
`hexo clean && hexo g`
