### ISSUE TITLE
删除插件文章路由变成undefined

### ISSUE THREAD

**Issue by cloudsmithy** [Rozbo/hexo-abbrlink#71]
删除插件之后,路由变成undefined,依赖文件夹已经删除,从package.json中删除,现在所有的路由都不正常,hexo clean 无效

http://localhost:4000/undefined/

**Comment by ohroy** [comment]
删除后配置里要改回去，:abbrlink 已经不再有效。
比如可以将
```yaml
permalink: posts/:abbrlink/ 
```
改为
```yaml
permalink: posts/:title/ 
```
以重新按标题生成链接

**Comment by cloudsmithy** [comment]
thanks
