### ISSUE TITLE
您好，请问如果标题修改了，生成的链接会变么？

### ISSUE THREAD

**Issue by yanzi1225627** [Rozbo/hexo-abbrlink#9]
如题

**Comment by ohroy** [comment]
这个和标题没有关系的，只是第一次生成的时候会以标题做种子生成一个id，此后链接生成后会保存在文章的头部，除非你手动修改它，否则它便不会被改变。

**Comment by YangAlas** [comment]
请问abbrlink后的连接undefined了，是什么原因

**Comment by iNorthIsle** [comment]
@rozbo 请问abbrlink后的连接undefined了，是什么原因

**Comment by drrui** [comment]
@YangAlas  我的也是，请问你找到原因了嘛？

**Comment by drrui** [comment]
@YangAlas  我新建了一篇文章，又都可以了。。。你试试。

**Comment by ohroy** [comment]
参考这里 #11 
主要原因是没有使用标准的font-matter
```
---
title: 名字
---
```

即上下都有`---`
